### ISSUE TITLE
How to add api functions to controller

### ISSUE THREAD

**Issue by divanvb** [ndelvalle/generator-api#22] opened 2016-12-09 13:25 UTC
Hi, can you please provide me with an example of how to implement a function or route for example getUser, I am struggling to figure out how to implement a function in the controller for example.

EDIT* What I'm basically asking is if you can provide me an example of how I would add a custom function that just returns some text.

**Comment by ndelvalle** [comment] 2016-12-09 16:12
If you use the generator with default attributes, you will end up with a `pet` and `user` model, so your routes file look like the following (More complete actually with the `pet` stuff, etc)

```javascript
const Router = require('express').Router;
const router = new Router();

const user  = require('./model/user/user-router');
router.use('/user', user);

module.exports = router;
```

After that, go to the `user/user-router.js` file you will find the route extensions, so all routes that you add here will be prefix with `user`, example:

```javascript
router.route('/active').get((...args) => controller.getActiveUsers(...args));
```

This route will be match when someone makes a `GET` request to `/user/active` (actually `http://yourserviceurl.com/user/active`)

what is happening here is that the `getActiveUsers` method from the controller is being called when that router is matched and all the `args` are passed along. 

Now we should implement this method in the controller file (`user/user-controller.js`). The following would be a good approach

```javascript
const Controller = require('../../lib/controller');
const userFacade = require('./user-facade');

class UserController extends Controller {
  getActiveUsers(req, res, next) {
    return this.facade.find({ active: true })
      .then(collection => res.status(200).json(collection))
      .catch(err => next(err));
  }
}

module.exports = new UserController(userFacade);
```

Note that the method above is using the Facade find method `this.facade.find` that does all the magic of actually requesting mongoose that stuff with that query.

Let me know if this helps you, or if you need more examples. I will generate a more real life project with the generator and upload it to the repo to show examples in the future.

**Comment by divanvb** [comment] 2016-12-09 17:14
Okay I understand what is happening now and I've tried to implement it, but server keeps responding with: CastError: Cast to ObjectId failed for value "test" at path "_id" for model "Users"

**Comment by ndelvalle** [comment] 2016-12-09 17:56
Can you provide the code that you are using, it seems that somewhere you are doing something like `_id: 'test'` and mongoose can not parse that cause is not a valid `id`.

**Comment by divanvb** [comment] 2016-12-09 18:35
user-controller:
const Controller = require('../../lib/controller');
const usersFacade  = require('./users-facade');

class UsersController extends Controller {
  test(req, res, next) {
    return this.facade.find({ active: true })
        .then(collection => res.status(200).json(collection))
        .catch(err => next(err));
  }
}

module.exports = new UsersController(usersFacade);


User-router:
const controller = require('./users-controller');
const Router = require('express').Router;
const router = new Router();

router.route('/')
  .get((...args) => controller.find(...args))
  .post((...args) => controller.create(...args));

router.route('/:id')
  .put((...args) => controller.update(...args))
  .get((...args) => controller.findById(...args))
  .delete((...args) => controller.remove(...args));

router.route('/test')
  .get((...args) => controller.test(...args));

module.exports = router;


Angular 2 service call: 

login() {
    return this.http.get('http://localhost:5000/users/test')
      .map(res => res.json())
      .catch(this.handleError);
  }

**Comment by divanvb** [comment] 2016-12-09 19:05
All the normal calls work, it's as soon as I create my own function it starts throwing me errors. No idea what is happening.

**Comment by ndelvalle** [comment] 2016-12-09 19:39
@divanvb the problem is that you are first specifying the `/:id` route before the `/active` route. Remember that express is based on router order declaration, that is way is matching the first route and then calling `findById` method with `active` as `_id`. Try defining the active route before the id one. Example:

```javascript
const controller = require('./users-controller');
const Router = require('express').Router;
const router = new Router();

router.route('/')
  .get((...args) => controller.find(...args))
  .post((...args) => controller.create(...args));

router.route('/test')
  .get((...args) => controller.test(...args));

router.route('/:id')
  .put((...args) => controller.update(...args))
  .get((...args) => controller.findById(...args))
  .delete((...args) => controller.remove(...args));

module.exports = router;
```

**Comment by divanvb** [comment] 2016-12-09 19:43
Ah that makes sense, sorry for the hassle but finished exams today and my brain is fried xD

**Comment by ndelvalle** [comment] 2016-12-09 19:45
No problem 🙂 let me know if everything is working for you so we can close the issue.

**Comment by divanvb** [comment] 2016-12-09 19:49
Yeah everything is working now, just got to try and setup passport for the first time to encrypt the password etc, never done it before so need to figure that out now with the server xD

**Closed** 2016-12-09 19:50 UTC

**Comment by ndelvalle** [comment] 2016-12-09 19:52
Cool! I would recommend these sctoch.io tutorials:
* [Easy Node Authentication](https://scotch.io/tutorials/easy-node-authentication-setup-and-local)
* [Easy Node Authentication: Facebook](https://scotch.io/tutorials/easy-node-authentication-facebook)

Let me know if you have trouble I can give a hand 👍

**Comment by ndelvalle** [comment] 2016-12-09 19:54
I actually like the approach of using `JSON Web Tokens` better, Ill recomend this [tutorial](https://scotch.io/tutorials/authenticate-a-node-js-api-with-json-web-tokens) In case you want to take a look.
